export { default as Login } from "../screens/AuthScreens/Login"
export { default as Register } from "../screens/AuthScreens/Register"
export { default as RegisterPassword } from "../screens/AuthScreens/RegisterPassword"
export { default as OtpForget } from "../screens/AuthScreens/forgetscreens/OtpForget"
export { default as PopUpStart } from "../screens/AuthScreens/SplashScreens/PopUpStart"
export { default as ForgetEmail } from "../screens/AuthScreens/forgetscreens/ForgetEmail"
export { default as SplashScreen } from "../screens/AuthScreens/SplashScreens/SplashScreen"
export { default as RegisterUserInformation } from "../screens/AuthScreens/RegisterUserInformation"
export { default as ForgetPhoneNumber } from "../screens/AuthScreens/forgetscreens/ForgetPhoneNumber"
export { default as ForgetConfirmPassword } from "../screens/AuthScreens/forgetscreens/ForgetConfirmPassword"

export { default as FAQ } from "../screens/HomeScreens/Setting/FAQ"
export { default as Setting } from "../screens/HomeScreens/Setting/Setting"
export { default as Notification } from "../screens/HomeScreens/Setting/Notification"
export { default as SubscriptionDetails } from "../screens/HomeScreens/Setting/SubscriptionDetails"
export { default as BlockUser } from "../screens/HomeScreens/Setting/BlockUser"
export { default as SettingsProfile } from "../screens/HomeScreens/Setting/SettingsProfile"
export { default as DeleteAccount } from "../screens/HomeScreens/Setting/DeleteAccount"

