export default NavigationString = {
    POPUP_START: "Popupstart",
    SPLASH_SCREEN: "SplashScreen",
    LOGIN: "Login",
    REGISTER: "Register",
    REGISTER_USER_INFO: "RegisterUserInformation",
    REGISTER_PASSWORD: "RegisterPassword",
    FORGET_EMAIL: "ForgetEmail",
    FORGET_PHONE_NO: "ForgetPhoneNumber",
    OTP_FORGET: "OtpForget",
    FORGET_CONFIRM_PASSWORD: "ForgetConfirmPassword",
    FRAME_CONTENT: "FrameContent",
    HOME: "Home",
    CATEGORIES: "Categories",
    PROFILE: "Profile",
    PLAY_STORY_TIME: "PlayStoryTime",
    FEED_CHAT: "Feedchat",
}
