export const Base_Url = 'http://storytime.yameenyousuf.com/api/';
export const register_endpoint = 'auth/register';
export const login_andpoint = 'auth/login';
export const reset_email_endpoint = 'auth/send-code';
export const reset_verify_code = 'auth/verify-code';
export const reset_password_endpoint = 'auth/reset-password';
export const stateandCity_endpoint = 'states';
export const city_andpoint = 'cities';
export const username_endpoint = 'user/check-availability';
export const category_endpoint = 'category';
export const Subcategory = '?parent=';
export const category_Random = "category/random";
export const storyfeed_Endpoint = "story";
export const storyLikedfeed = "story/like/:"
export const getAllUsers_endpoint = "user"
export const follow_Unfollow_endpoint = "user/follow-toggle"
export const addComment_endpoint = "story/add-comment"
export const getComment_endpoint = "story/comments/:"
export const block_list_endpoint = "user/block-list"
export const unblock_endpoint = "user/block"
export const notifications_endpoint = "user/notifications"
export const logout_endpoint = "auth/logout"
export const user_profile = "user/profile"

